name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: zip
      run: zip -r -y /home/runner/work/Glowing/Glowing/libs/Glowing-OF.zip /home/runner/work/Glowing/Glowing/Glowing-OF
    - name: zip
      run: zip -r -y /home/runner/work/Glowing/Glowing/libs/Glowing-CTM.zip /home/runner/work/Glowing/Glowing/Glowing-CTM
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Glowing-OF
        path: libs/
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Glowing-CTM
        path: libs/
