name: release-artifacts

on:
  release:
    types:
     - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup python 3.13
        uses: actions/setup-python@v5
        with:
            python-version: 3.13
      - name: Get & Install requirements 
        run: |
          chmod +x packwrapper.sh
          ./packwrapper.sh reqGen
          ./packwrapper.sh reqInstl
      - name: Build artifact
        run: |
          ./packwrapper.sh build
      - name: Upload release
        uses: AButler/upload-release-assets@v3.0.1
        with:
          files: '/**/.packwrapper/package/*.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}