name: transform

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11
            - name: Install dependencies & Run transformer
              run: |
                python -m pip install --upgrade pip
                pip install pillow
                python transformer.py

            - name: Commit and push changes
              uses: Andro999b/push@v1.3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                message: 'change: transform default to labPBR'
                branch: ${{ github.ref_name }}